WebApplication7/Models/SkiResortModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WebApplication7.Models
{
    public class SkiResortModel
    {
        public int Id { get; set; }

        [DisplayName("Название курорта")]
        public string Name { get; set; }

        [DisplayName("Город")]
        public string City { get; set; }

        [DisplayName("Дата открытия")]
        [DataType(DataType.Date)]
        public DateTime OpenDate { get; set; }

        [DisplayName("Количество горнолыжных трасс")]
        public int NumberOfSkiSlopes { get; set; }

        [DisplayName("Средняя длина трассы")]
        public double AverageSlopeLength { get; set; }

        [DisplayName("Ежегодный общий доход")]
        public decimal AnnualRevenue { get; set; }
    }
}

WebApplication7/Controllers/SkiResortController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using WebApplication7.Models;

public class SkiResortController : Controller
{
    private static List<SkiResortModel> skiResorts = new List<SkiResortModel>()
    {
        new SkiResortModel { Id = 1, Name = "Роза Хутор", City = "Сочи", OpenDate = new DateTime(2011, 11, 24), NumberOfSkiSlopes = 102, AverageSlopeLength = 1350, AnnualRevenue = 2100000000 },
        new SkiResortModel { Id = 2, Name = "Гора Аибга", City = "Красная поляна", OpenDate = new DateTime(2014, 1, 4), NumberOfSkiSlopes = 75, AverageSlopeLength = 1590, AnnualRevenue = 1700000000 },
        new SkiResortModel { Id = 3, Name = "Эльбрус", City = "Терек", OpenDate = new DateTime(1958, 12, 28), NumberOfSkiSlopes = 11, AverageSlopeLength = 4400, AnnualRevenue = 600000000 }
    };

    private void AddSkiResortToList(SkiResortModel skiResort)
    {
        skiResort.Id = skiResorts.Count + 1;
        skiResorts.Add(skiResort);
    }


    public ActionResult Index()
    {
        return View(skiResorts.ToList());
    }

    [HttpGet]
    public ActionResult Create()
    {
        return View();
    }

    [HttpPost]
    public ActionResult Create(SkiResortModel skiResort)
    {
        if (ModelState.IsValid)
        {
            AddSkiResortToList(skiResort);
            return RedirectToAction("Index");
        }
        return View(skiResort);
    }

}

WebApplication7/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

WebApplication7/Views/SkiResort/Create.cshtml
@model WebApplication7.Models.SkiResortModel

<h2>Добавление нового курорта</h2>

@using (Html.BeginForm("Create", "SkiResort", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-group">
        @Html.LabelFor(model => model.Name, new { @class = "control-label" })
        @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.City, new { @class = "control-label" })
        @Html.TextBoxFor(model => model.City, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.OpenDate, new { @class = "control-label" })
        @Html.EditorFor(model => model.OpenDate, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.OpenDate, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.NumberOfSkiSlopes, new { @class = "control-label" })
        @Html.EditorFor(model => model.NumberOfSkiSlopes, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.NumberOfSkiSlopes, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.AverageSlopeLength, new { @class = "control-label" })
        @Html.EditorFor(model => model.AverageSlopeLength, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.AverageSlopeLength, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.AnnualRevenue, new { @class = "control-label" })
        @Html.EditorFor(model => model.AnnualRevenue, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.AnnualRevenue, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        <input type="submit" value="Добавить" class="btn btn-primary" />
    </div>
}

<div>
    @Html.ActionLink("Назад к списку курортов", "Index")
</div>

WebApplication7/Views/SkiResort/Index.cshtml
@using WebApplication7.Models
@model List<SkiResortModel>

@helper RenderSkiResortsTable(List<SkiResortModel> resorts)
{
    <table>
        <thead>
            <tr>
                <th>Название курорта</th>
                <th>Город</th>
                <th>Дата открытия</th>
                <th>Количество горнолыжных трасс</th>
                <th>Средняя длина трассы</th>
                <th>Ежегодный общий доход</th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @while (resorts.Any())
            {
                var skiResort = resorts.First();
                resorts.Remove(skiResort);

                <tr>
                    <td>@Html.DisplayFor(modelItem => skiResort.Name)</td>
                    <td>@Html.DisplayFor(modelItem => skiResort.City)</td>
                    <td>@Html.DisplayFor(modelItem => skiResort.OpenDate)</td>
                    <td>@Html.DisplayFor(modelItem => skiResort.NumberOfSkiSlopes)</td>
                    <td>@Html.DisplayFor(modelItem => skiResort.AverageSlopeLength)</td>
                    <td>@Html.DisplayFor(modelItem => skiResort.AnnualRevenue)</td>
                </tr>
            }
        </tbody>
    </table>
}

<h1>Лыжные курорты</h1>

@if (Model.Any())
{
    @RenderSkiResortsTable(Model)
}
else
{
    <p>Нет данных.</p>
}

<div>
    @Html.ActionLink("Добавить новый курорт", "Create")
</div>